const WORD_PER_PAGE_AMOUNT = 20
const MAX_AUDIOCALL_ANSWERS_AMOUNT = 5
const PAGES_PER_GROUP = 30

const DOMAIN_URL = process.env.REACT_APP_DOMAIN as string

export { WORD_PER_PAGE_AMOUNT, MAX_AUDIOCALL_ANSWERS_AMOUNT, PAGES_PER_GROUP, DOMAIN_URL }
